### ISSUE TITLE
[preprocess.py] Code in line 56&57 is inconsistent with the sample csv data

### ISSUE THREAD

**Issue by zeng-yifei** [johnny12150/GC-SAN#1]
Data in sample_train-item-views.csv use `session_id`& `item_id` as the column name . But the code in line 56 & 57 is like `data['session_id'] = data.pop('sessionId')` .This will lead to error when testing  sample data. So the code should be modified as `data['session_id'] = data.pop('session_id')` and `data['item_id'] = data.pop('item_id')`. The error disappeared and the code produces sample txt file normally after this modification👍

**Comment by johnny12150** [comment]
The preprocessing part is taken from the SR-GNN repo.
It seems like an old bug.
Thanks for the reminder!
