### ISSUE TITLE
多头注意力

### ISSUE THREAD

**Issue by aaaaaaui** [johnny12150/GC-SAN#3]
作者您好，您的注意力机制在使用时很方便，但是多头注意力怎么运行不起来，是这样就可以吗
self.multihead_attn = MultiHeadedAttention(4, self.hidden_size, 0.2).cuda()

**Comment by lizhi317** [comment]
> 您好，请问您这个跑起来了么

**Comment by lizhi317** [comment]
> 作者您好，您的注意力机制在使用时很方便，但是多头注意力怎么运行不起来，是这样就可以吗 self.multihead_attn = MultiHeadedAttention(4, self.hidden_size, 0.2).cuda()
您好，您这个多头注意力机制跑起来了么

**Comment by lizhi317** [comment]
> Hello, the author, your attention mechanism is very convenient to use, but how can the multi attention work? Is this OKself.multihead_attn = MultiHeadedAttention(4, self.hidden_size, 0.2).cuda()

您这个跑起来了么

**Comment by johnny12150** [comment]
> > Hello, the author, your attention mechanism is very convenient to use, but how can the multi attention work? Is this OKself.multihead_attn = MultiHeadedAttention(4, self.hidden_size, 0.2).cuda()
> 
> 您这个跑起来了么

This bug should have been fixed now.
For more detail, you can check out [this commit](https://github.com/johnny12150/GC-SAN/commit/6231d3e1a7d4d169d599df71b74c9be91e4e1741).
